// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlpevaojdtggphxvttaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRscGV2YW9qZHRnZ3BoeHZ0dGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MTQxMDgsImV4cCI6MjA3NzM5MDEwOH0.NXTY-SswiKtKkjLhgoodi2j1hdKUwksphdOSmtMhKvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});